version: '2.3'
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: sse-notification:develop
    depends_on:
      - rabbitmq
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000 # This is development setup only
    stdin_open: true
    tty: true

  rabbitmq:
    image: rabbitmq:3.8-management
    environment:
      - RABBITMQ_DEFAULT_USER=local
      - RABBITMQ_DEFAULT_PASS=mypass
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - 15672:15672

volumes:
  rabbitmqdata:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.172.181.0/24
          gateway: 10.172.181.1
